### ISSUE TITLE
Interesting Auto Refresh 

### ISSUE THREAD

**Issue by dineshmaxi-web** [rrkishoreraj/REplit-Classroom-Analytics-APp#2]
It's kinda auto refreshing feature enabled? If so, May I know why? If not, It's auto refreshing after few seconds (Note: There is no submission add-ons on a screen after auto refresh) why?

**Comment by rrkishoreraj** [comment]
Yes!. The auto-refreshing feature is been enabled. It refreshes every 20 seconds. And the reason why **no submission** add-ons on the screen is that as of now, there are no submissions happening around!. Once it takes place, then you could see that the students will get displayed on the leader board. 

Though there are no submissions, you could still see the students who had submitted prior. Just go ahead and click the **search assignments** field, you could see the list of assignments (it's just a test data). Clicking on one of the assignments will display the winners of that assignment.

**Comment by dineshmaxi-web** [comment]
If I am not wrong, The app will check the submissions for every 20 seconds. If it happened, that will be rendered!

Suggestion : You can avoid refreshing the whole page by using the socket.io (Which we mostly used in the chat apps)
